/** @format */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import DashboardSidebar from "@/components/CommonComponents/DashboardSidebar";
import NavBar from "@/components/CommonComponents/NabBar";
import { UserRoleProvider } from "@/contexts/UserRoleContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gafbi Health Care Dashboard",
  description: "Generated by Rahul Mallik",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserRoleProvider>
          <SidebarProvider>
            <DashboardSidebar />
            <SidebarInset className="overflow-x-hidden">
              <NavBar />
              <div
                className={` bg-root-bg min-h-screen px-6 lg:px-8 py-1 lg:py-2`}
              >
                {children}
              </div>
            </SidebarInset>
          </SidebarProvider>
        </UserRoleProvider>
      </body>
    </html>
  );
}
